export const settings = {
  dogSpeed: 3,
  neighborSpeed: 2,
  redBullState: "onlyMove",
  clockState: "onlyMove",
  clockState2: "move",
  guardWearingGloves: false,
  guardWearingBoots: false,
  guardProgress: 42,
  rukusProgress: 0,
  bigDoorAlarmAnimationState: "closedLights",
  lastDoorAlarmAnimationState: "closed",
  guardBootsColor: "none",
  guardGlovesColor: "none",
  glovesColor: "blue",
  bootsColor: "blue",
  stopped: false,
  isMusicPlaying: true,
};
